apiVersion: v1
kind: Service
metadata:
  name: prometeusz
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
   app: promoperator-prometheus-op-prometheus