apiVersion: v1
kind: Service
metadata:
  name: prometeusz
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
   app.kubernetes.io/name: grafana