apiVersion: v1
kind: Service
metadata:
  name: prometeusz
  annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: prometheus-grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80